# Generated by Django 4.1.10 on 2023-07-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_mywebpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mywebpage',
            options={'verbose_name': 'Web Page with video'},
        ),
    ]
