# Generated by Django 4.1.10 on 2023-07-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_articleindexpage_body_alter_articlepage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywebpage',
            name='content',
        ),
    ]
