# Generated by Django 4.1.10 on 2023-07-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_mywebpage_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyWebPage',
        ),
    ]
